### ISSUE TITLE
Add other informative priors

### ISSUE THREAD

**Issue by domenicrosati** [d4l3k/go-bayesopt#1]
I have a function whose inputs are is normaly distrbuted,
I have another whose inputs are exponentially distributed,
We should be able to add the following informative prior distrubutions as parameters:
- Normal
- Expontential

**Comment by d4l3k** [comment]
It should be pretty easy to implement new priors. I only implemented a uniform param since that's all I currently need, but you can write any prior you want that satisfies the Param interface. 

https://godoc.org/github.com/d4l3k/go-bayesopt#Param

For a normally distributed param you can just sample from a normal distribution instead.

**Comment by d4l3k** [comment]
Just added https://godoc.org/github.com/d4l3k/go-bayesopt#NormalParam

**Comment by d4l3k** [comment]
ExponentialParam https://godoc.org/github.com/d4l3k/go-bayesopt#ExponentialParam

If you need something more complex, let me know! Or you can just write your own sampling param

**Comment by domenicrosati** [comment]
wow you were quick!

**Comment by domenicrosati** [comment]
thanks a lot for this, I really appreciate it, I was just about to make PRs!
